db:
  port: 54313
  password: dontask
  database: identidad_db
server:
  prefix_idafe: dontask
install:
  table-data-dir:
    - install-example
devel:
  useFileDevelopment: true
  delay: 400
  cache-content: true
  forceShowAsEditable: false      