db:
  port: 54313
  password: dontask
  database: identidad_db
server:
  prefix_idafe: dontask
  prefix_idope: dontask
  mainDomain: http://127.0.0.1:3021
install:
  table-data-dir:
    - install-example
devel:
  useFileDevelopment: true
  delay: 400
  cache-content: true
  forceShowAsEditable: false
login:
  forget:
    urlPath: /forget
    mailFields: [mail, mail_alternativo]
mailer:
  motor: smtp
  conn:
    host: smtp.nuestrosvn.com
    port: 465
    secure: true
    auth: 
      user: cambiar@nuestrosvn.com
      pass: cambiar
  mail-info:
    from: '"Nombre y apellido" <cambiar@nuestrosvn.com>'
  supervise: 
    to:
      - cambiar@cambiar.com
    event:
      restart-ok: true
      restart-fail: true
